### ISSUE TITLE
Sound library needs to be worked on.

### ISSUE THREAD

**Issue by OliAnime** [marcolovescode/SRB2-emscripten#31]
The sound library for the port seems a little out of wack, as it sounds as if the instrumentation is wrong. I assume this difference comes from the sound library, or the old sound library from 2.1 has been imported and needs to be replaced.

The latter of the two options seems the most likely.

**Comment by marcolovescode** [comment]
Which platform are you running on? (PC, iOS, Android?)

And do you mean music, or sound effects?

**Comment by OliAnime** [comment]
I didn't notice sound effect differences, but I did notice the music. I am running it on Firefox (PC) and have tested it on Chrome (PC) with similar results.

**Comment by marcolovescode** [comment]
Thanks for reporting; this is because the port uses MIDI music by default, instead of digital music like the official game.

Since you're on PC, you can disable "Low-End" mode to use digital music.

![image](https://user-images.githubusercontent.com/297483/95124555-9b8daa80-0721-11eb-9437-a3477f1e1d07.png)

(I have a plan in the works to use digital music by default, but this will take a little while.)
